added Octokit and dotenv, some revisions
Lexxicus/TestGuru pull request #13
Opened 2020-12-22 17:47 UTC by Lexxicus

2020-12-23 19:10 UTC, BubuntuClu requested changes

2020-12-23 19:10 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +      if result
проверяй не наличие ответа, а код выполнения запроса в октокит по созданию гиста. в октоките есть метод `last_response`, на его основе сделай метод `success?` в клиенте

2020-12-23 19:10 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    if @gist
вложенные ифы это плохо, разбей логику на методы. и вообще стоит ли запрещать создавать только один гист для пользователя на вопрос?

2020-12-23 19:10 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +  before_action :set_test_passage, :set_question
так работает? чет не пробовал несколько методов указывать так)

2020-12-23 19:10 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +  before_action :find_gist, only: %i[create]
почему гист находишь только для `create`, а остальные методы без ограничения на экшены?

2020-12-23 19:10 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    @question = @test_passage.current_question
не очень хорошо завязыватся на последовательность методов в колбэках, поменяли случайно порядок и все упало.

зачем эти методы вообще нужны, если ты их вызываешь только один раз в самом экшене?

2020-12-23 19:10 UTC, BubuntuClu commented on app/views/admin/gists/_gist.html.erb
> +</tr>
в IDE сделай настройку чтобы пустая строка добавлялась в конец файла

2020-12-24 19:32 UTC, BubuntuClu requested changes

2020-12-24 19:32 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +      gist = client.call
как это так? ты проверяешь сначала был ли успешно создан гист на гитхабе, а только потом его там создаешь? тут напутан порядок действий. ты сначала создаешь гист, а потом проверяешь успешно ли он там был создан

2020-12-25 06:45 UTC, BubuntuClu requested changes

2020-12-25 06:45 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    client = GistQuestionService.new(@question).call
```
client =  GistQuestionService.new(@question)
result = client.call
if client.success?
  ...
```

2020-12-25 06:45 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    if @gist.save!
если ты используешь бэнг-метод, то должен быть `rescue` блок чтобы словить ошибку, которую можешь тут получить иначе у тебя просто упадет приложение

2020-12-25 06:48 UTC, Lexxicus commented on app/controllers/gists_controller.rb
> +    if @gist.save!
Это было временное решение для теста пишется в базу или нет, забыл убрать

2020-12-25 06:49 UTC, Lexxicus commented on app/controllers/gists_controller.rb
> +    client = GistQuestionService.new(@question).call
Аааааааааа, всё пазл сложился

2020-12-25 09:15 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    if @gist.save!
ну это понятно что временное решение, но это надо убирать перед пушем

2020-12-26 15:04 UTC, merged